
# Use the acc-py-devtools templates found at
# https://gitlab.cern.ch/-/ide/project/acc-co/devops/python/acc-py-devtools/blob/master/-/acc_py_devtools/templates/gitlab-ci/python.yml.
include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: pyda
  PY_VERSION: '3.7'

  ACCSOFT_DS_MODEL_REPO:
    value: "acc-co/devops/python/prototypes/accsoft-ds-model-py"
    description: "The repo project name for pyds-model"

  ACCSOFT_DS_MODEL_REF:
    value: "master"
    description: "The ref to use from $ACCSOFT_DS_MODEL_REPO to test against."


# Pull pyds_model wheel and install before running any dependent jobs
.model_dep:
  variables:
    PIP_FIND_LINKS: ./wheelhouse/
  needs:
    - project: "${ACCSOFT_DS_MODEL_REPO}"
      job: build_wheel
      ref: "${ACCSOFT_DS_MODEL_REF}"
      artifacts: true


build_wheel:
  extends: .acc_py_build_wheel


test_wheel:
  extends:
    - .model_dep
    - .acc_py_wheel_test
  needs:
    - !reference [.model_dep, needs]
    - build_wheel


# A development installation of pyda tested with pytest.
test_dev:
  extends:
    - .model_dep
    - .acc_py_dev_test


# A push of the source distribution to the acc-py PyPI, only on git tag.
release_sdist_on_tag:
  extends: .acc_py_release_sdist


release_wheel:
  extends: .acc_py_release_wheel


# A dev build of the documentation, made available through cern.ch/acc-py.
build_docs:
  extends:
    - .model_dep
    - .acc_py_build_docs


# A release build of the documentation, made available through cern.ch/acc-py.
build_docs_on_tag:
  extends: .acc_py_build_docs_on_tag


pre-commit:
  extends: .acc_py_pre-commit
